<section class="px-3 px-lg-5 pt-3 pt-lg-5" style="background-color: var(--color-1);">
      <div class="container">
        <div class="row text-center">
          <div class="col-lg-12 my-2 my-lg-3 pt-5">
            <div class="card-body">
              <p class="card-text  mb-1 tt-upper">Our Blog</p>
              <h2 class="card-title header-font mb-3">Recent From Blog</h2>
            </div>
          </div>
        </div>


        <div class="row row-cols-1 row-cols-lg-2 g-2 p-3 p-lg-5">
          <div class="col">
            <div class="card border-0 blog-1 rounded-0">
              <div class="row g-0">
                <div class="col-sm-6 text-center">
                  <img src="images/mcf-flower-3.png" class="img-fluid" alt="MCF's Chenille Stems flower three.">
                </div>
                <div class="col-sm-6">
                  <div class="card-body">
                    <p class="card-text d-flex">
                    <ul class="ul-list ms-3">
                      <li>
                        <i class="bi bi-person-fill-check mx-1"></i>Admin
                        <i class="bi bi-calendar mx-1"></i>01.21.24
                      </li>
                      <li>
                        <i class="bi bi-chat-dots-fill mx-1"></i>Comments
                      </li>
                    </ul>
                    </p>
                    <h4 class="card-title"><a href="our-blog.php" class="mcf-blog">Card title</a></h4></a>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>

                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="card border-0 blog-1 rounded-0">
              <div class="row g-0">
                <div class="col-sm-6 text-center">
                  <img src="images/mcf-flower-3.png" class="img-fluid" alt="MCF's Chenille Stems flower three.">
                </div>
                <div class="col-sm-6">
                  <div class="card-body">
                    <p class="card-text d-flex">
                    <ul class="ul-list ms-3">
                      <li>
                        <i class="bi bi-person-fill-check mx-1"></i>Admin
                        <i class="bi bi-calendar mx-1"></i>01.21.24
                      </li>
                      <li>
                        <i class="bi bi-chat-dots-fill mx-1"></i>Comments
                      </li>
                    </ul>
                    </p>
                    <h4 class="card-title"><a href="our-blog.php" class="mcf-blog">Card title</a></h4></a>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="card border-0 blog-1 rounded-0">
              <div class="row g-0">
                <div class="col-sm-6">
                  <div class="card-body">
                    <p class="card-text d-flex">
                    <ul class="ul-list ms-3">
                      <li>
                        <i class="bi bi-person-fill-check mx-1"></i>Admin
                        <i class="bi bi-calendar mx-1"></i>01.21.24
                      </li>
                      <li>
                        <i class="bi bi-chat-dots-fill mx-1"></i>Comments
                      </li>
                    </ul>
                    </p>
                    <h4 class="card-title"><a href="our-blog.php" class="mcf-blog">Card title</a></h4></a>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  </div>
                </div>
                <div class="col-sm-6 text-center">
                  <img src="images/mcf-flower-3.png" class="img-fluid" alt="MCF's Chenille Stems flower three.">
                </div>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="card border-0 blog-1 rounded-0">
              <div class="row g-0">
                <div class="col-sm-6">
                  <div class="card-body">
                    <p class="card-text d-flex">
                    <ul class="ul-list ms-3">
                      <li>
                        <i class="bi bi-person-fill-check mx-1"></i>Admin
                        <i class="bi bi-calendar mx-1"></i>01.21.24
                      </li>
                      <li>
                        <i class="bi bi-chat-dots-fill mx-1"></i>Comments
                      </li>
                    </ul>
                    </p>
                    <h4 class="card-title"><a href="our-blog.php" class="mcf-blog">Card title</a></h4></a>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  </div>
                </div>
                <div class="col-sm-6 text-center">
                  <img src="images/mcf-flower-3.png" class="img-fluid" alt="MCF's Chenille Stems flower three.">
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>