<article aria-label="footer nav bar">
    <!-- Bottom Navbar -->
    <nav class="navbar navbar-expand-lg mcf-navbar-dark" aria-label="Bottom navigation">
        <div class="container">
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#bottomNavBar" aria-controls="bottomNavBar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="pe-2">Bottom Menu</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="bottomNavBar">
                <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link px-2" href="accessibility.php">Accessibility</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2" href="terms-of-service.php">Terms of Service</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2" href="privacy.php">Privacy Policy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2" href="sitemap.php">Sitemap</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</article>