<footer>

    <section class="bg-one p-5">
        <div class="container-xl">
            <div class="row justify-content-between">
                <div class="col-md-4 col-lg px-3">
                    <div class="card-title-footer mb-4">
                        <h2 class="d-flex header-font">
                            <a class="navbar-brand" href="index.html">Millie's Crazy Flowers</a>
                        </h2>
                        <p>Legacy of love, caring, and lasting friendship from one friend to another</p>
                        <ul class="li-inline ul-lst" mt-4"="">
                            <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                            <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                            <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4 col-lg px-3">
                    <div class="card-title-footer mb-4">
                        <h2 class="header-font">Recent Posts</h2>
                        <div class="block-8 mb-4 d-flex">
                            <a class="blog-img rounded" style="background-image: url(images/image_1.jpg);"></a>
                            <div class="text">
                                <div class="fs-9">
                                    <div><a href="#"><i class="bi bi-calendar"></i></span>date submitted</a></div>
                                    <div><a href="#"><i class="bi bi-person-fill-check"></i> First name</a></div>
                                </div>
                                <p class="heading"><a href="#">Message title</a></p>
                            </div>
                        </div>
                        <div class="block-8 mb-4 d-flex">
                            <a class="blog-img rounded" style="background-image: url(images/image_2.jpg);"></a>
                            <div class="text">
                                <div class="fs-9">
                                    <div><a href="#"><i class="bi bi-calendar"></i></span> Date submitted</a></div>
                                    <div><a href="#"><i class="bi bi-person-fill-check"></i> First name</a></div>
                                </div>
                                <p class="heading"><a href="#">Message title</a></p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-lg px-3">
                    <div class="card-title-footer mb-4">
                        <h2 class="header-font">Have a Questions?</h2>
                        <div class="text mb-3">
                            <ul>
                                <li><i class="bi bi-map"></i><span class="text">P.O. Box 5040, Valley Springs, California, 93933, USA</span></li>

                                <li><a href="#"><i class="bi bi-send"></i><span class="text">info@yourdomain.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="footer-image">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <p>Copyright © 2024 Millie's Crazy Flowers. All Rights Reserved.
            </p>
        </div>
    </section>

</footer>

<!-- Bootstrap JavaScript Libraries -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>