<div class="col-lg-4 col-sm-12 col-12">
    <h3 class="fw-bold mb-3">Once Upon A Time</h3>
    <p class="mb-3 mb-lg-5">We believe storytelling establishes common ground and empathy. Do you want to share a your story about pipe cleaners and/or love with us? If so, please email <a href="mailto:<?php echo getenv('mcf-info-email'); ?>" class="mcf-link  fw-bold"><?php echo getenv('mcf-info-email'); ?> </a> </p>


    <h3 class="fw-bold mb-3">Recent Posts</h3>
    <div class="block-8 d-flex mb-3">
        <a class="nl-img rounded" style="background-image: url(images/special-day.png);"></a>

        <ul class="ul-list ms-3">
            <li class="fs-14">
                <i class="bi bi-calendar me-1"></i>04.22.24
                <i class="bi bi-person-fill-check mx-1"></i>Jeanne E.
            </li>
            <li>
                <p class="ps-2 h6"><a href="newsletter-april-2024.php" class="mcf-nl ">Handcrafted Elegance for Every Occasion</a></p>
            </li>
        </ul>
    </div>

    <div class="block-8 d-flex mb-3 mb-lg-5">
        <a class="nl-img rounded" style="background-image: url(images/nl-img-jan-2024.png);"></a>

        <ul class="ul-list ms-3">
            <li class="fs-14">
                <i class="bi bi-calendar me-1"></i>01.15.24
                <i class="bi bi-person-fill-check mx-1"></i>Anonymous
            </li>
            <li>
                <p class="ps-2 h6"><a href="newsletter-jan-2024.php" class="mcf-nl ">Bending Love: The Artistry of Pipe Cleaners</a></p>
            </li>
        </ul>
    </div>


    <h3 class="fw-bold mb-3">Join Us on Social Media</h3>
    <div class="d-flex mb-3 mb-lg-5"">
                            <ul class=" ul-list display-2">
        <li class="li-horizontal">
            <a href="https://www.pinterest.com/littlebee0794/_created/" class="sm-color" target="_blank"><i class="bi bi-pinterest"></i></a>
        </li>
        <li class="li-horizontal">
            <a href="https://www.instagram.com/littlebee0714/?hl=en" class="sm-color" target="_blank"><i class="bi bi-instagram"></i></a>
        </li>
        <!--
        <li class="li-horizontal">
            <a href="#" class="sm-color"><i class="bi bi-facebook"></i></a>
        </li>
        -->
        </ul>
    </div>


    <h3 class="fw-bold mb-3"> Our Gallery</h3>
    <div class="d-flex mb-3 mb-lg-5">
        <a href=purchase.php>
            <img src="images/mcf-flower-6.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower six." title="Zooming in!">
        </a>
        <a href=purchase.php>
            <img src="images/mcf-flower-8.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower eight." title="Zooming in!">
        </a>

    </div>

</div>