<aside aria-label="Newsletter right column">
    <div class="col-lg-4 col-sm-12 col-12">
        <section aria-label="Brief about us">
            <h3 class="fw-bold mb-3">Once Upon A Time</h3>
            <p class="mb-3 mb-lg-5">We believe storytelling establishes common ground and empathy. Do you want to share a your story about pipe cleaners and/or love with us? If so, please email <a href="mailto:<?php echo getenv('mcf-info-email'); ?>" class="mcf-link  fw-bold"><?php echo getenv('mcf-info-email'); ?> </a> </p>
        </section>

        <section aria-label="Newsletter List">
            <h3 class="fw-bold mb-3">Recent Posts</h3>
        </section>
        <div class="block-8 d-flex mb-3">
            <div class="nl-img rounded" style="background-image: url(images/special-day.png);"></div>

            <ul class="ul-list ms-3">
                <li class="fs-14">
                    <i class="bi bi-calendar me-1"></i>04.22.24
                    <i class="bi bi-person-fill-check mx-1"></i>Jeanne E.
                </li>
                <li>
                    <p class="ps-2 h6"><a href="newsletter-april-2024.php" class="mcf-nl ">Handcrafted Elegance for Every Occasion</a></p>
                </li>
            </ul>
        </div>

        <div class="block-8 d-flex mb-3 mb-lg-5">
            <div class="nl-img rounded" style="background-image: url(images/nl-img-jan-2024.png);"></div>

            <ul class="ul-list ms-3">
                <li class="fs-14">
                    <i class="bi bi-calendar me-1"></i>01.15.24
                    <i class="bi bi-person-fill-check mx-1"></i>Anonymous
                </li>
                <li>
                    <p class="ps-2 h6"><a href="newsletter-jan-2024.php" class="mcf-nl ">Bending Love: The Artistry of Pipe Cleaners</a></p>
                </li>
            </ul>
        </div>

        <section aria-label="Social media">
            <h3 class="fw-bold mb-3">Join Us on Social Media</h3>
        </section>
        <div class="d-flex mb-3 mb-lg-5">
            <ul class=" ul-list display-2">
                <li class="li-horizontal">
                    <a href="https://www.pinterest.com/littlebee0794/_created/" class="sm-color" target="_blank"><i class="bi bi-pinterest" aria-hidden="true"></i><span class="sr-only">(Opens a new window to Pinterest)</span></a>
                </li>

                <li class="li-horizontal">
                    <a href="https://www.instagram.com/littlebee0714/?hl=en" class="sm-color" target="_blank"><i class="bi bi-instagram" aria-hidden="true"></i><span class="sr-only">(Opens a new window to Instagram)</span></a>
                </li>

                <li class="li-horizontal">
                    <a href="#" class="sm-color"><i class="bi bi-facebook" aria-hidden="true"></i><span class="sr-only">(Opens a new window to Facebook)</span></a>
                </li>

            </ul>
        </div>


        <a href="index.php#discover" class="mcf-link">
            <h3 class="fw-bold mb-3">Our Gallery</h3>
        </a>
        <div class="d-flex flex-wrap mb-3 mb-lg-5">
            <img src="images/mcf-flower-6.png" class="img-fluid-sm l-box" alt="MCF's Chenille Stems flower six." title="Zooming in!">

            <img src="images/mcf-flower-1.png" class="img-fluid-sm l-box" alt="MCF's Chenille Stems flower one." title="Zooming in!">

            <img src="images/mcf-flower-2.png" class="img-fluid-sm l-box" alt="MCF's Chenille Stems flower two." title="Zooming in!">

            <img src="images/mcf-flower-8.png" class="img-fluid-sm l-box" alt="MCF's Chenille Stems flower eight." title="Zooming in!">

        </div>

    </div>
</aside>