<div class="col-lg-4 col-sm-12 col-12">
    <h3 class="fw-bold mb-3">Once Upon A Time</h3>
    <p class="mb-3 mb-lg-5">We believe storytelling establishes common ground and empathy. Do you want to share a your story about pipe cleaners and/or love with us? If so, please email <a href="mailto:<?php echo getenv('mcf-info-email'); ?>" class="mcf-link  fw-bold"><?php echo getenv('mcf-info-email'); ?> </a> </p>


    <h3 class="fw-bold mb-3">Recent Posts</h3>
    <div class="block-8 d-flex mb-3">
        <a class="nl-img rounded" style="background-image: url(images/mcf-flower-2.png);"></a>

        <ul class="ul-list ms-3">
            <li class="fs-14">
                <i class="bi bi-calendar me-1"></i>02.14.24
                <i class="bi bi-person-fill-check mx-1"></i>First name
            </li>
            <li>
                <h6 class="ps-2"><a href="newsletter-feb-2024.php" class="mcf-nl ">February title</a></h6>
            </li>
        </ul>
    </div>

    <div class="block-8 d-flex mb-3 mb-lg-5">
        <a class="nl-img rounded" style="background-image: url(images/nl-img-jan-2024.png);"></a>

        <ul class="ul-list ms-3">
            <li class="fs-14">
                <i class="bi bi-calendar me-1"></i>01.15.24
                <i class="bi bi-person-fill-check mx-1"></i>First name
            </li>
            <li>
                <h6 class="ps-2"><a href="newsletter-jan-2024.php" class="mcf-nl ">Bending Love: The Artistry of Pipe Cleaners</a></h6>
            </li>
        </ul>
    </div>


    <h3 class="fw-bold mb-3">Join Us on Social Media</h3>
    <div class="d-flex mb-3 mb-lg-5"">
                            <ul class=" ul-list display-2">
        <li class="li-horizontal">
            <a href="#" class="sm-color"><i class="bi bi-pinterest"></i></a>
        </li>
        <li class="li-horizontal">
            <a href="#" class="sm-color"><i class="bi bi-instagram"></i></a>
        </li>
        <li class="li-horizontal">
            <a href="#" class="sm-color"><i class="bi bi-facebook"></i></a>
        </li>
        </ul>
    </div>


    <h3 class="fw-bold mb-3"> Our Gallery</h3>
    <div class="d-flex mb-3 mb-lg-5">
        <a href=purchase.php> <img src="images/mcf-flower-1.png" class="img-fluid" alt="MCF's Chenille Stems flower one."></a>
        <a href=purchase.php><img src="images/mcf-flower-1.png" class="img-fluid" alt="MCF's Chenille Stems flower one."></a>
    </div>

</div>