<article class="px-3 px-lg-5 pt-3 pt-lg-5" style="background-color: var(--color-1);" aria-label="Our finished projects">
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col-lg-12 my-2 my-lg-3 pt-5">
            <div class="card-body">
              <p class="card-text  mb-1 tt-upper">Our Finished Projects</p>
              <section aria-label="Flower collection">
                <h2 class="card-title header-font mb-3">Crazy Flower Collection</h2>
                <p class="card-text small mb-1"><strong>Note</strong>: Flowers only are sold not including vases, cards, or trinkets.</p>
              </section>
            </div>
          </div>
        </div>

        <div class="row text-center align-btm">
          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-5.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower five." title="Zooming in!">
          </div>

          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-6.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower six." title="Zooming in!">
          </div>

          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-7.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower seven." title="Zooming in!">
          </div>

          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-8.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower eight." title="Zooming in!">
          </div>

          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-9.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower nine." title="Zooming in!">
          </div>

          <div class="col-lg-2 p-1 info-2 border border-white">
            <img src="images/mcf-flower-10.png" class="img-fluid l-box" alt="MCF's Chenille Stems flower ten." title="Zooming in!">
          </div>
        </div>
        
        <div class="text-center py-2">
          <p class="card-text   tt-upper">(Click to zoom in)</p>
        </div>

        <div class=" text-center pt-4 pb-5">
          <a href="purchase.php" class="btn mcf-button p-3 fs-5">Order Now</a>
        </div>

      </div>
    </article>