<article class="px-3 px-lg-5 pt-3 pt-lg-5" style="background-color: var(--color-1);" aria-label="Our Articles">
  <div class="container">
    <div class="row text-center">
      <div class="col-lg-12 my-2 my-lg-3 pt-5">
        <div class="card-body">
          <p class="card-text  mb-1 tt-upper">Our Articles</p>
          <section aria-label="Recent Newsletters">
            <h2 class="card-title bswash-font mb-3">Recent Newsletter</h2>
          </section>
        </div>
      </div>
    </div>


    <div class="row row-cols-1 row-cols-lg-2 g-2 p-3 p-lg-5">
      <div class="col">
        <div class="card border-0 nl-1 rounded-0 h-100">
          <div class="row g-0 shadow">
            <div class="col-sm-6 text-center">
              <img src="../images/special-day.png" class="figure-img img-fluid" alt="Hand written Special Day logo with a red heart.">
            </div>
            <div class="col-sm-6">
              <div class="card-body">
                <div class="card-text d-flex">
                  <ul class="ul-list ms-3">
                    <li>
                      <i class="bi bi-person-fill-check mx-1" aria-hidden="true"></i>Jeanne E.
                      <i class="bi bi-calendar mx-1" aria-hidden="true"></i>04.22.24
                    </li>
                    <li>
                      <i class="bi bi-chat-dots-fill mx-1" aria-hidden="true"></i>Comments
                    </li>
                  </ul>
                </div>
                <p class="card-title h4"><a href="newsletter-april-2024.php" class="mcf-nl ">Handcrafted Elegance for Every Occasion</a></p>
                <p class="card-text">Millie's Crazy Flowers offer a whimsical and delightful addition to any occasion. Read more here.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card border-0 nl-1 rounded-0 h-100">
          <div class="row g-0 shadow">
            <div class="col-sm-6 text-center">
              <img src="../images/nl-img-jan-2024.png" class="img-fluid">
            </div>
            <div class="col-sm-6">
              <div class="card-body">
                <div class="card-text d-flex">
                  <ul class="ul-list ms-3">
                    <li>
                      <i class="bi bi-person-fill-check mx-1" aria-hidden="true"></i>Anonymous
                      <i class="bi bi-calendar mx-1" aria-hidden="true"></i>01.28.24
                    </li>
                    <li>
                      <i class="bi bi-chat-dots-fill mx-1" aria-hidden="true"></i>Comments
                    </li>
                  </ul>
                </div>
                <p class="card-title h4"><a href="newsletter-jan-2024.php" class="mcf-nl ">Bending Love: The Artistry of Pipe Cleaners</a></p>
                <p class="card-text">Find out more info about pipe cleaners, whimsical sculptures, and love.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>