<article class="counter-show px-3 pt-3 pt-lg-5 mb-5" style="background-color: var(--color-9);" aria-label="Sales info">
  <div class="container">
    <div class="row text-center">
      <div class="col-lg-12 my-2 my-lg-3 pt-5">
        <div class="card-body">
          <p class="card-text  mb-1 tt-upper">Reviews About Our Flowers</p>
          <section aria-label="Detailed numbers">
            <h2 class="card-title bswash-font">Technical Statistics</h2>
          </section>
        </div>
      </div>
    </div>

    <div class="row text-center ">
      <div class="col-md-6 col-lg-3 my-3 my-lg-5">
        <div class="card-body">
          <div class="card-title tech-stat-numb mb-4">
            <div class="timer count-number" aria-labelledby="yoe">1</div>
          </div>
          <p id="yoe" class="card-text"><small class="text-body-secondary fw-bold tt-upper">Year of Experience</small></p>
        </div>
      </div>

      <div class="col-md-6 col-lg-3 my-3 my-lg-5">
        <div class="card-body">
          <div class="card-title tech-stat-numb mb-4">
            <div class="timer count-number" aria-labelledby="sc">5</div>
          </div>
          <p id='sc' class="card-text"><small class="text-body-secondary fw-bold tt-upper">Satisfied Customers</small></p>
        </div>
      </div>

      <div class="col-md-6 col-lg-3 my-3 my-lg-5">
        <div class="card-body">
          <div class="card-title tech-stat-numb mb-4">
            <div class="timer count-number" aria-labelledby="fc">103</div>
          </div>
          <p id="fc" class="card-text"><small class="text-body-secondary fw-bold tt-upper">Flowers Completed</small></p>
        </div>
      </div>

      <div class="col-md-6 col-lg-3 mt-3 my-lg-5 mb-5">
        <div class="card-body">
          <div class="card-title tech-stat-numb mb-4">
            <div class="timer count-number" aria-labelledby="ga">0</div>
          </div>
          <p id="ga" class="card-text"><small class="text-body-secondary fw-bold tt-upper">Get Awards</small></p>
        </div>
      </div>
    </div>
  </div>
</article>