<section class="px-0 px-lg-5 pt-3 pt-lg-5">
      <div class="container">
        <div class="row text-center">
          <div class="col-lg-12 my-2 my-lg-3 pt-5">
            <div class="card-body">
              <p class="card-text  mb-1 tt-upper">Testimonial</p>
              <h2 class="card-title header-font mb-3">Return Customers</h2>
            </div>
          </div>
        </div>


        <div id="carouselExampleAuto" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner pt-2">
            <div class="carousel-item p-3 active">
              <div class="d-flex justify-content-center">

                <div class="card c-shadow mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-md-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-lg-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>
              </div>
            </div>


            <div class="carousel-item p-3">
              <div class="d-flex justify-content-center">
                <div class="card c-shadow mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-md-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-lg-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>
              </div>
            </div>


            <div class="carousel-item p-3">
              <div class="d-flex justify-content-center">
                <div class="card c-shadow mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-md-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>

                <div class="card c-shadow d-none d-lg-block mx-3">
                  <div class="card-header">
                    <h6 class="card-title text-center pt-2"><strong>Rated 4.5 out of 5 stars</strong></h6>
                  </div>
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p class="card-text">A well-known quote, contained in a blockquote element.</p>
                      <footer class="blockquote-footer">Reviewed by <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                    <div class="text-end">
                      <a href="#" class="btn mcf-button mcf-btn-sm" role="button" data-bs-toggle="button">View</a>
                    </div>
                  </div>
                  <div class="card-footer text-body-secondary">
                    Commented on 01.24.24
                  </div>
                </div>
              </div>
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAuto" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAuto" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>

          </div>
        </div>
      </div>
    </section>